import { sqliteTable, text } from "drizzle-orm/sqlite-core";

// ...existing code...

export const files = sqliteTable("files", {
  // ...existing code...
  cloudKey: text("cloud_key"),
  // ...existing code...
});

// ...existing code...
